### ISSUE TITLE
Jade is now Pug

### ISSUE THREAD

**Issue by riyadhalnur** [IonicaBizau/blah#33]
Jade went through a name change not too long ago to Pug. It's recommended to switch over to Pug now.

**Comment by IonicaBizau** [comment]
@riyadhalnur Ah, nice! :grin: I will solve this soon unless you guys are faster than me. :smile: Contributions are welcome!

**Comment by riyadhalnur** [comment]
@IonicaBizau I'll send in a PR today 😃

**Comment by IonicaBizau** [comment]
That would be great! :sparkles:
