### ISSUE TITLE
A few improvements to help strings and README.md

### ISSUE THREAD

**Issue by silviubogan** [IonicaBizau/blah#47]
Take this string in [DOCUMENTATION.md#searchfile-callback][1] as an example:

> to search in the templates directories (in the following order: local .blah directory, ~/.blah-templates, library templates).

I think these pieces of information are essential so they should be put in the `--help` string and once this is done, the copy of the CLI help string in `README.md` should be updated.

  [1]: https://github.com/IonicaBizau/blah/blob/master/DOCUMENTATION.md#searchfile-callback

Do you agree, @IonicaBizau? :smiley:

**Comment by IonicaBizau** [comment]
It can be part of the `notes` property. You can add a multiline string (using backticks).

```js
notes: `Lorem ipsum ...

Happy Blahing!
`
```

https://github.com/IonicaBizau/blah/blob/ac747e7af271716508106b7c70d83c2d6bd97c76/bin/blah#L72

**Comment by silviubogan** [comment]
Done in #49.

**Comment by IonicaBizau** [comment]
🚢 **`3.2.0`** Thanks!
