### ISSUE TITLE
When running commands such as "blah -r" the location of the used template should be printed

### ISSUE THREAD

**Issue by silviubogan** [IonicaBizau/blah#48]
Do you agree, @IonicaBizau? :smiley:

**Comment by IonicaBizau** [comment]
I'm afraid that would create too much noise in the output.

**Comment by IonicaBizau** [comment]
Maybe let's keep this opened and if some other people will request it, it's something we can easily add. I won't vote for it.

**Comment by IonicaBizau** [comment]
This is simple enough: if `~/.blah-templates/README.ajs` is missing, the default template will be used.
