### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [IonicaBizau/blah#53]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by IonicaBizau** [comment]
This is amazing! :grin: I may use it in another project. After a quick look, I guess it has some limitations.

The focus here isn't the speed, but the flexibility.
I was actually thinking to switch to `ajs`, since it would support async calls: https://github.com/IonicaBizau/ajs

**Comment by IonicaBizau** [comment]
Implemented ajs support for the `README` template. This will allow us to have asynchronous calls inside of the template.
